In [1]:
import numpy as np
import torch

In [2]:
x = torch.Tensor(3,2).long()

In [3]:
x

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [7]:
x = torch.ones(3,3).long()
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [22]:
x = x.view(1,-1)
print(x,x.shape)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]]) torch.Size([1, 9])


In [21]:
x = x.squeeze()
print(x,x.shape)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1]) torch.Size([9])


In [29]:
x = x.unsqueeze(dim=0)
x = x.unsqueeze(dim=0)
print(x,x.shape)

tensor([[[[[[[[[[[[[[1, 1, 1, 1, 1, 1, 1, 1, 1]]]]]]]]]]]]]]) torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9])
